include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

stages:
  - build 
  - test
  - cleanup
  - scan

# Build and push the frontend image
build_frontend:
  stage: build
  image: docker:26.0.1
  services:
    - docker:26.0.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME -f ./frontend/Dockerfile ./frontend
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME

# Build and push the backend image
build_backend:
  stage: build
  image: docker:26.0.1
  services:
    - docker:26.0.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME -f ./backend/Dockerfile ./backend
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME

e2e-test:
  stage: test
  image: docker:26.0.1-dind  # Use the dind image for running Docker commands
  services:
    - docker:26.0.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose rm -f
    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
    - docker-compose --profile e2etest up --build --abort-on-container-exit

unit-test:
  stage: test
  image: docker:26.0.1-dind  # Use the dind image for running Docker commands
  services:
    - docker:26.0.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
    - docker-compose --profile unittest up --build --abort-on-container-exit

# Trivy Scans
frontend_scan:
  stage: scan
  variables:
    SECURE_LOG_LEVEL: 'debug'
    CS_IMAGE: '$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME'
    GIT_STRATEGY: 'fetch'
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE

backend_scan:
  stage: scan
  variables:
    SECURE_LOG_LEVEL: 'debug'
    CS_IMAGE: '$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME'
    GIT_STRATEGY: 'fetch'
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE

cleanup:
  stage: cleanup
  image: docker:26.0.1
  script:
    - docker rmi $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME;
    - docker rmi $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME;
  when: always
