version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
  backend:
    build: ./backend
      # volumes:
      # - ./backend:/code  # Mount so I can see the changes reflect immediately inside the container
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=postgresql://db_user:db_pass@db/enigma_db
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=enigma_db
