services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=postgresql://db_user:db_pass@db/enigma_db
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=enigma_db

  cypress: # Only needed when running cypress open 
    #  build:
    #   context: ./frontend
    #   dockerfile: Cypress.Dockerfile
    image: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
    depends_on: # Correct depends_on syntax
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:8080
    working_dir: /e2e
    command: npx cypress open
    profiles:
      - testing
        # entrypoint: [ "bun", "cypress", "run" ]


  test:
    build: ./backend
    volumes:
      - ./backend/app:/code/app  # Mount to reflect changes in tests immediately
    command: sh -c 'sleep 3 && pytest -s /code/app/user_tests.py'
    depends_on:
      - backend
      - db
    environment:
      - SQLALCHEMY_SILENCE_UBER_WARNING=1  # Silence SQLAlchemy 2.0 compatibility warning
